FORMAT: 1A

# IP_Project
An API for https://github.com/CritZap/IP_project


## Tweet Collection [/posts]


### Get all tweets [GET]
+ Response 200 (application/json)

        [
            { 
                "id": 1,
                "user": "User 1",
                "text": "Burp"

            },
            
            { 
                "id": 2,
                "user": "Random Guy",
                "text": "jumping jacks"

            },
            
            { 
                "id": 3,
                "user": "Dev",
                "text": "Code code code code code"

            },
            
            {
                "id": 4,
                "user": "BigBen",
                "text": "Chaps"

            }
        ]
        


### Post a tweet [POST]

+ text (string) - Text.

+ Request (application/json)

        { 
            "text": "Something"
        }

+ Response 201 (application/json)

    + Headers

            Location: /posts/5

    + Body
    
            { 
                "id": 5, 
                "user": "New Guy",
                "text": "Greetings !" 
            }
            
            { 
                "id": 6, 
                "user": "Ollld",
                "text": "Bye Bye !" 
            }

       
## Posts [/posts/{id}]


+ Parameters
    + id (required, number, `1`) ... id of a post in form of an integer


### Delete a tweet [DELETE]

+ Response 204
