FORMAT: 1A

# IP_Project
An API for https://github.com/CritZap/IP_project


## Tweet Collection [/posts]

### List all tweets [GET]
+ text (string) - Text.
+ Response 200 (application/json)

        [
            { 
                "text": "Burp"

            },
            
            { 
                "text": "LeBurp"

            },
            
            { 
                "text": "BeBurp"

            },
            
            {
                "text": "Deburp"

            }
        ]
        

### Create a tweet [POST]

+ text (string) - Text.

+ Request (application/json)

        { 
            "text": "Burp"
        }

+ Response 201 (application/json)

    + Headers

            Location: /posts/1

    + Body
    
            { 
                "id": 1, 
                "title": "Post1",
                "url": "/posts/1",
                "text": "Burp" 
            }

## Posts [/posts/{id}]


+ Parameters
    + id (required, number, `1`) ... id of a post in form of an integer
        


### Delete a tweet [DELETE]

+ Response 204
